import { Product } from "./types";

export const seedProducts: Product[] = [
  // Women's Beauty
  {
    id: "w-001",
    name: "Radiant Shea Glow Body Butter",
    brand: "Zuldal Naturals",
    category: "women",
    price: 8500,
    compareAtPrice: 10500,
    shortDescription: "Whipped shea butter for deep hydration and glow.",
    description:
      "A rich, whipped body butter made from unrefined shea, sweet almond oil and vitamin E. Melts into skin instantly, leaving a soft, radiant glow without any greasy residue. Suitable for all skin types.",
    tags: ["Hydrating", "Natural", "All Skin Types"],
    icon: "jar",
    imageUrls: [],
    stock: 34,
    rating: 4.8,
    reviewsCount: 212,
    featured: true,
    createdAt: "2026-05-02",
  },
  {
    id: "w-002",
    name: "Vitamin C Brightening Serum",
    brand: "Lumière Skin",
    category: "women",
    price: 12000,
    shortDescription: "20% Vitamin C serum for an even, brighter tone.",
    description:
      "A fast-absorbing serum formulated with 20% stabilized Vitamin C, hyaluronic acid and licorice root extract to fade dark spots, even skin tone and boost radiance over time.",
    tags: ["Brightening", "Hydrating", "Cruelty Free"],
    icon: "droplet",
    imageUrls: [],
    stock: 51,
    rating: 4.7,
    reviewsCount: 168,
    featured: true,
    createdAt: "2026-04-18",
  },
  {
    id: "w-003",
    name: "Silk Edge Laminating Brow Gel",
    brand: "Bloom Cosmetics",
    category: "women",
    price: 6200,
    shortDescription: "All-day brow hold with a soft, brushed-up finish.",
    description:
      "A clear, flexible-hold gel that laminates and sets brows in place for up to 16 hours. Infused with castor oil to condition brow hairs while you wear it.",
    tags: ["Long Wear", "Cruelty Free"],
    icon: "sparkles",
    imageUrls: [],
    stock: 60,
    rating: 4.5,
    reviewsCount: 94,
    createdAt: "2026-03-30",
  },
  {
    id: "w-004",
    name: "Black Soap Detox Cleansing Bar",
    brand: "Zuldal Naturals",
    category: "women",
    price: 4200,
    shortDescription: "African black soap for a deep, gentle cleanse.",
    description:
      "Handmade with raw African black soap, shea butter and honey. Draws out impurities and excess oil while leaving skin soft and calm — safe for daily use on face and body.",
    tags: ["Natural", "Safe", "All Skin Types"],
    icon: "jar",
    imageUrls: [],
    stock: 78,
    rating: 4.6,
    reviewsCount: 143,
    createdAt: "2026-02-14",
  },
  {
    id: "w-005",
    name: "Silk Wrap Edge Control & Hair Gel",
    brand: "Crown & Coil",
    category: "women",
    price: 5000,
    shortDescription: "Strong hold edge control for sleek styles.",
    description:
      "A non-flaking edge control that lays hair down smoothly and holds through humidity. Formulated with castor oil and aloe to nourish the scalp.",
    tags: ["Long Wear", "Natural"],
    icon: "droplet",
    imageUrls: [],
    stock: 45,
    rating: 4.4,
    reviewsCount: 77,
    createdAt: "2026-01-22",
  },

  // Men's Grooming
  {
    id: "m-001",
    name: "Charcoal Deep Clean Face Wash",
    brand: "Zuldal Men",
    category: "men",
    price: 5800,
    shortDescription: "Activated charcoal face wash for oily skin.",
    description:
      "Purifies pores and controls oil with activated charcoal and tea tree oil, without stripping skin. Leaves a fresh, matte finish — ideal for daily grooming routines.",
    tags: ["Safe", "All Skin Types"],
    icon: "droplet",
    imageUrls: [],
    stock: 58,
    rating: 4.6,
    reviewsCount: 121,
    featured: true,
    createdAt: "2026-05-10",
  },
  {
    id: "m-002",
    name: "Beard Growth & Conditioning Oil",
    brand: "Zuldal Men",
    category: "men",
    price: 7200,
    shortDescription: "Lightweight oil for a fuller, softer beard.",
    description:
      "A blend of jojoba, argan and castor oils that softens coarse beard hair, soothes the skin underneath and supports healthier growth over time.",
    tags: ["Natural", "Hydrating"],
    icon: "jar",
    imageUrls: [],
    stock: 40,
    rating: 4.7,
    reviewsCount: 156,
    createdAt: "2026-04-02",
  },
  {
    id: "m-003",
    name: "Energizing Body Wash for Men",
    brand: "Terra Grooming",
    category: "men",
    price: 4600,
    shortDescription: "Menthol-infused wash for an energizing shower.",
    description:
      "A cooling body wash with mint, eucalyptus and sea salt extract that leaves skin refreshed and lightly scented all day long.",
    tags: ["Safe", "Hydrating"],
    icon: "droplet",
    imageUrls: [],
    stock: 66,
    rating: 4.3,
    reviewsCount: 58,
    createdAt: "2026-03-11",
  },
  {
    id: "m-004",
    name: "Matte Finish Daily Moisturizer",
    brand: "Zuldal Men",
    category: "men",
    price: 6400,
    shortDescription: "Oil-free hydration with a shine-free finish.",
    description:
      "A lightweight, fast-absorbing moisturizer with SPF-friendly base and niacinamide to hydrate skin while keeping shine under control all day.",
    tags: ["Hydrating", "All Skin Types"],
    icon: "shield",
    imageUrls: [],
    stock: 49,
    rating: 4.5,
    reviewsCount: 82,
    createdAt: "2026-02-27",
  },

  // Wellness
  {
    id: "wl-001",
    name: "Detox Herbal Wellness Tea",
    brand: "Zuldal Wellness",
    category: "wellness",
    price: 5200,
    shortDescription: "A calming daily blend of moringa, ginger & lemongrass.",
    description:
      "A caffeine-free herbal tea blend crafted to support digestion and daily detox. Steep and sip as part of a calming morning or evening ritual.",
    tags: ["Natural", "Safe"],
    icon: "leaf",
    imageUrls: [],
    stock: 90,
    rating: 4.6,
    reviewsCount: 133,
    featured: true,
    createdAt: "2026-05-20",
  },
  {
    id: "wl-002",
    name: "Vitamin C + Zinc Effervescent Tablets",
    brand: "VitaCore",
    category: "wellness",
    price: 6800,
    shortDescription: "Daily immunity support, 20 effervescent tablets.",
    description:
      "A great-tasting effervescent tablet packed with Vitamin C, Zinc and Vitamin D3 to support daily immune health. Just drop, dissolve and drink.",
    tags: ["Safe", "Natural"],
    icon: "shield",
    imageUrls: [],
    stock: 74,
    rating: 4.5,
    reviewsCount: 97,
    createdAt: "2026-04-09",
  },
  {
    id: "wl-003",
    name: "Muscle Recovery & Massage Balm",
    brand: "Zuldal Wellness",
    category: "wellness",
    price: 7400,
    shortDescription: "Soothing balm for post-workout recovery.",
    description:
      "A warming balm with arnica, eucalyptus and menthol that eases tension in tired muscles and joints after exercise or a long day.",
    tags: ["Natural", "Hydrating"],
    icon: "dumbbell",
    imageUrls: [],
    stock: 38,
    rating: 4.7,
    reviewsCount: 64,
    createdAt: "2026-03-05",
  },
  {
    id: "wl-004",
    name: "Deep Sleep Support Gummies",
    brand: "VitaCore",
    category: "wellness",
    price: 8900,
    shortDescription: "Melatonin & chamomile gummies for restful sleep.",
    description:
      "Fall asleep naturally with a gentle blend of melatonin, chamomile and L-theanine. Non-habit forming and gentle enough for nightly use.",
    tags: ["Natural", "Safe"],
    icon: "heart",
    imageUrls: [],
    stock: 55,
    rating: 4.4,
    reviewsCount: 71,
    createdAt: "2026-01-18",
  },

  // Perfumes
  {
    id: "p-001",
    name: "Oud Noir Eau de Parfum",
    brand: "Maison Zuldal",
    category: "perfumes",
    price: 32000,
    compareAtPrice: 38000,
    shortDescription: "A bold, smoky oud fragrance with amber depth.",
    description:
      "An intense, long-lasting fragrance built around dark oud, amber and warm spice notes. A unisex signature scent for evening wear that lasts from dusk till dawn.",
    tags: ["Long Wear", "Cruelty Free"],
    icon: "bottle",
    imageUrls: [],
    stock: 22,
    rating: 4.9,
    reviewsCount: 184,
    featured: true,
    createdAt: "2026-05-15",
  },
  {
    id: "p-002",
    name: "Blush Bloom Eau de Parfum",
    brand: "Maison Zuldal",
    category: "perfumes",
    price: 28500,
    shortDescription: "A soft floral scent with rose and peony petals.",
    description:
      "A delicate floral bouquet of rose, peony and white musk, designed for everyday wear with a soft sillage that lingers gently through the day.",
    tags: ["Long Wear", "Natural"],
    icon: "bottle",
    imageUrls: [],
    stock: 30,
    rating: 4.7,
    reviewsCount: 112,
    createdAt: "2026-04-22",
  },
  {
    id: "p-003",
    name: "Citrus Vetiver Cologne",
    brand: "Terra Grooming",
    category: "perfumes",
    price: 21000,
    shortDescription: "A crisp, fresh cologne for daytime wear.",
    description:
      "A fresh, energizing blend of bergamot, grapefruit and vetiver — light enough for daily office wear, sharp enough to stand out.",
    tags: ["Long Wear", "All Skin Types"],
    icon: "bottle",
    imageUrls: [],
    stock: 41,
    rating: 4.5,
    reviewsCount: 88,
    createdAt: "2026-02-08",
  },
  {
    id: "p-004",
    name: "Velvet Amber Travel Perfume Set",
    brand: "Maison Zuldal",
    category: "perfumes",
    price: 18500,
    shortDescription: "3 x 15ml travel-size amber fragrances.",
    description:
      "A trio of miniature amber-based fragrances perfect for travel or gifting, each with a distinct warm, cozy character.",
    tags: ["Long Wear"],
    icon: "bottle",
    imageUrls: [],
    stock: 26,
    rating: 4.6,
    reviewsCount: 53,
    createdAt: "2026-01-30",
  },

  // Turaren Wuta
  {
    id: "tw-001",
    name: "Turare Amber Musk Fragrance Oil",
    brand: "Gidauniya Turare",
    category: "turaren-wuta",
    price: 9500,
    shortDescription: "Classic amber musk oil-based turaren wuta.",
    description:
      "A traditional Northern Nigerian oil-based fragrance blending amber, musk and warm woods. Long-lasting on skin and fabric, cherished for generations.",
    tags: ["Long Wear", "Natural"],
    icon: "flame",
    imageUrls: [],
    stock: 47,
    rating: 4.8,
    reviewsCount: 139,
    featured: true,
    createdAt: "2026-05-08",
  },
  {
    id: "tw-002",
    name: "Bakhoor Oud Wood Chips",
    brand: "Gidauniya Turare",
    category: "turaren-wuta",
    price: 7800,
    shortDescription: "Fragrant bakhoor wood chips for home & clothing.",
    description:
      "Premium oud-soaked bakhoor wood chips, burned to perfume homes, clothing and special occasions with a deep, smoky, long-lasting scent.",
    tags: ["Natural", "Long Wear"],
    icon: "flame",
    imageUrls: [],
    stock: 63,
    rating: 4.7,
    reviewsCount: 101,
    createdAt: "2026-03-19",
  },
  {
    id: "tw-003",
    name: "Rose Ittar Attar Oil",
    brand: "Zuwara Attars",
    category: "turaren-wuta",
    price: 8600,
    shortDescription: "Pure rose attar, alcohol-free and long lasting.",
    description:
      "A concentrated, alcohol-free rose attar oil rooted in traditional perfumery. A few drops offer hours of soft, floral fragrance.",
    tags: ["Natural", "Long Wear", "All Skin Types"],
    icon: "flame",
    imageUrls: [],
    stock: 52,
    rating: 4.6,
    reviewsCount: 76,
    createdAt: "2026-02-25",
  },
  {
    id: "tw-004",
    name: "Sandalwood & Spice Turare Blend",
    brand: "Zuwara Attars",
    category: "turaren-wuta",
    price: 10200,
    shortDescription: "Warm sandalwood turare with clove & spice notes.",
    description:
      "A warm, grounding blend of sandalwood, clove and traditional spice notes — a modern take on a heritage turaren wuta recipe.",
    tags: ["Natural", "Long Wear"],
    icon: "flame",
    imageUrls: [],
    stock: 35,
    rating: 4.8,
    reviewsCount: 64,
    createdAt: "2026-01-12",
  },
];
